// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/shopify.ts";
import * as $$$$$$$$$$$3 from "./apps/site.ts";
import * as $$$0 from "./loaders/availableIcons.ts";
import * as $$$1 from "./loaders/icons.ts";
import * as $$$$$$0 from "./sections/Component.tsx";
import * as $$$$$$1 from "./sections/Header.tsx";
import * as $$$$$$2 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$3 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/availableIcons.ts": $$$0,
    "site/loaders/icons.ts": $$$1,
  },
  "sections": {
    "site/sections/Component.tsx": $$$$$$0,
    "site/sections/Header.tsx": $$$$$$1,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$2,
    "site/sections/Theme/Theme.tsx": $$$$$$3,
  },
  "apps": {
    "site/apps/deco/analytics.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/deco/shopify.ts": $$$$$$$$$$$2,
    "site/apps/site.ts": $$$$$$$$$$$3,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
